name: publish website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
    - name: Build the Website
      run: |
        cd website
        yarn install --frozen-lockfile
        yarn run build

    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/build # The folder the action should deploy.
